site_name: mimi site

theme:
  name: dracula
  favicon: favicon.png
  logo: favicon.png

nav:
    - Главная: index.md
    - Об авторе: author_info.md
    - Лабораторные работы: labs.md

    - More: more.md
    